### ISSUE TITLE
CAS txn support

### ISSUE THREAD

**Issue by jakobdalsgaard** [vdloo/consul-kv#13]
Hi, I'm trying to do some cas txn support, would that be some work you're interested in?

/Jakob

**Comment by vdloo** [comment]
PRs are appreciated. I don't use cas myself but it looks trivial to change consul-kv to use it additionally to `set`. I haven't looked that deep into it but it looks like the verb [here](https://github.com/vdloo/consul-kv/blob/master/consul_kv/api.py#L67) should maybe just be a named parameter of `put_kx_tn` so you can pass `verb='cas'` instead of `verb='set'`. Please do add a simple unit test [here](https://github.com/vdloo/consul-kv/blob/8e66e98e836d08666047a46b782649a0d6e6d4da/tests/unit/api/test_put_txn.py#L25) if you create a pr.

**Comment by jakobdalsgaard** [comment]
Cool, I'll try that :-)

**Comment by jakobdalsgaard** [comment]
Tada, did a PR :-)

**Comment by vdloo** [comment]
Thanks @jakobdalsgaard, a new version (0.5) of this library containing your changes is now [available on pypi](https://pypi.python.org/pypi/consul_kv/).

**Comment by jakobdalsgaard** [comment]
Cool - thanks - unfortunately my git fu wasn't that good -- I'm missing some %s -> format :/

Should I make a new PR.

**Comment by vdloo** [comment]
No worries, cleaned some stuff up [here](https://github.com/vdloo/consul-kv/pull/15/files) already

**Comment by jakobdalsgaard** [comment]
Thanks, stupid me, was cleaning up my local branch and it wouldn't let me
due to uncommitted changes :/

Den 24. jun. 2017 13.01 skrev "Rick van de Loo" <notifications@github.com>:

**Comment by MaxymVlasov** [comment]
So, you make breaking changes from 0.4 to 0.5.

In my case now nothing work - only create `tnx` Key in root of Consul KV.

@vdloo, you didn't any release info of changes to README.

So, I just reuse 0.4
```bash
pip install https://pypi.python.org/packages/e0/98/5003c51b50aedbad6dee49b49d359ef0f03ef4947b2ae81f59c43d84c149/consul_kv-0.4.tar.gz
```

**Comment by vdloo** [comment]
@MaxymVlasov oops sorry, didn't realize people were actually using this project except me. I'll add a changelog from now on. It is always a good idea to pin your pip requirements if you have projects where you don't want things to change without notice. I don't employ any semantic versioning, this is rolling release. If a version of a pip module works for you you can do `pip freeze | grep thatmodule` and for example put thatmodule==0.4 in your requirements.txt. I had to change the default endpoint to not have /kv attached to it because otherwise it wouldn't allow you to use get_meta. See https://github.com/vdloo/consul-kv/pull/20 and https://github.com/vdloo/consul-kv/pull/22.

**Comment by vdloo** [comment]
Added a changelog here https://github.com/vdloo/consul-kv/pull/24 @MaxymVlasov. Closing this issue now because the CAS support has been added.
